### PR TITLE
Bump dependency bounds.

### PR DESCRIPTION
**Pull request by alaendle**
Support GHC-9.8 - `cabal test` and `stack test` succeed (not tested against older GHC versions). Maybe time to create a new revison on hackage? Thanks for providing this library!

(cc @F-Joachim)

### CODE REVIEW

**Comment by alaendle** [comment]
Would also resolve #7 and #8.

**Comment by alaendle** [comment]
And also a new release/revsion on hackage would semi-automatically re-enable the package in stackage nightly.

**Review by cocreature — APPROVED** [review]
Thank you!

**Comment by cocreature** [comment]
I've uploaded 0.3.4 which includes this.

**Pull request merged**
